<?php

namespace Database\Seeders;

use App\Models\EventCategory;
use App\Models\EventTemplate;
use Illuminate\Database\Seeder;

class EventTemplateSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $track = EventCategory::where('code', 'track')->first();
        $field = EventCategory::where('code', 'field')->first();
        $funGames = EventCategory::where('code', 'fun_games')->first();

        $templates = [
            [
                'event_category_id' => $track->id,
                'name' => '100m',
                'type' => 'individual',
                'gender' => 'male',
                'category' => 'all',
                'max_participants' => 1,
                'has_qualifying_round' => true,
                'has_multiple_attempts' => false,
                'attempts_count' => 1,
                'is_relay' => false,
                'order' => 1,
            ],
            [
                'event_category_id' => $track->id,
                'name' => '100m',
                'type' => 'individual',
                'gender' => 'female',
                'category' => 'all',
                'max_participants' => 1,
                'has_qualifying_round' => true,
                'has_multiple_attempts' => false,
                'attempts_count' => 1,
                'is_relay' => false,
                'order' => 2,
            ],
            [
                'event_category_id' => $track->id,
                'name' => '200m',
                'type' => 'individual',
                'gender' => 'male',
                'category' => 'all',
                'max_participants' => 1,
                'has_qualifying_round' => true,
                'has_multiple_attempts' => false,
                'attempts_count' => 1,
                'is_relay' => false,
                'order' => 3,
            ],
            [
                'event_category_id' => $track->id,
                'name' => '200m',
                'type' => 'individual',
                'gender' => 'female',
                'category' => 'all',
                'max_participants' => 1,
                'has_qualifying_round' => true,
                'has_multiple_attempts' => false,
                'attempts_count' => 1,
                'is_relay' => false,
                'order' => 4,
            ],
            [
                'event_category_id' => $track->id,
                'name' => '400m',
                'type' => 'individual',
                'gender' => 'male',
                'category' => 'all',
                'max_participants' => 1,
                'has_qualifying_round' => true,
                'has_multiple_attempts' => false,
                'attempts_count' => 1,
                'is_relay' => false,
                'order' => 5,
            ],
            [
                'event_category_id' => $track->id,
                'name' => '400m',
                'type' => 'individual',
                'gender' => 'female',
                'category' => 'all',
                'max_participants' => 1,
                'has_qualifying_round' => true,
                'has_multiple_attempts' => false,
                'attempts_count' => 1,
                'is_relay' => false,
                'order' => 6,
            ],
            [
                'event_category_id' => $track->id,
                'name' => '800m',
                'type' => 'individual',
                'gender' => 'male',
                'category' => 'all',
                'max_participants' => 1,
                'has_qualifying_round' => false,
                'has_multiple_attempts' => false,
                'attempts_count' => 1,
                'is_relay' => false,
                'order' => 7,
            ],
            [
                'event_category_id' => $track->id,
                'name' => '800m',
                'type' => 'individual',
                'gender' => 'female',
                'category' => 'all',
                'max_participants' => 1,
                'has_qualifying_round' => false,
                'has_multiple_attempts' => false,
                'attempts_count' => 1,
                'is_relay' => false,
                'order' => 8,
            ],
            [
                'event_category_id' => $track->id,
                'name' => '1500m',
                'type' => 'individual',
                'gender' => 'male',
                'category' => 'all',
                'max_participants' => 1,
                'has_qualifying_round' => false,
                'has_multiple_attempts' => false,
                'attempts_count' => 1,
                'is_relay' => false,
                'order' => 9,
            ],
            [
                'event_category_id' => $track->id,
                'name' => '1500m',
                'type' => 'individual',
                'gender' => 'female',
                'category' => 'all',
                'max_participants' => 1,
                'has_qualifying_round' => false,
                'has_multiple_attempts' => false,
                'attempts_count' => 1,
                'is_relay' => false,
                'order' => 10,
            ],
            [
                'event_category_id' => $track->id,
                'name' => '4x100m',
                'type' => 'relay',
                'gender' => 'male',
                'category' => 'all',
                'max_participants' => 4,
                'has_qualifying_round' => true,
                'has_multiple_attempts' => false,
                'attempts_count' => 1,
                'is_relay' => true,
                'order' => 11,
            ],
            [
                'event_category_id' => $track->id,
                'name' => '4x100m',
                'type' => 'relay',
                'gender' => 'female',
                'category' => 'all',
                'max_participants' => 4,
                'has_qualifying_round' => true,
                'has_multiple_attempts' => false,
                'attempts_count' => 1,
                'is_relay' => true,
                'order' => 12,
            ],
            [
                'event_category_id' => $track->id,
                'name' => '4x400m',
                'type' => 'relay',
                'gender' => 'male',
                'category' => 'all',
                'max_participants' => 4,
                'has_qualifying_round' => true,
                'has_multiple_attempts' => false,
                'attempts_count' => 1,
                'is_relay' => true,
                'order' => 13,
            ],
            [
                'event_category_id' => $track->id,
                'name' => '4x400m',
                'type' => 'relay',
                'gender' => 'female',
                'category' => 'all',
                'max_participants' => 4,
                'has_qualifying_round' => true,
                'has_multiple_attempts' => false,
                'attempts_count' => 1,
                'is_relay' => true,
                'order' => 14,
            ],
            [
                'event_category_id' => $field->id,
                'name' => 'Lontar Peluru',
                'type' => 'individual',
                'gender' => 'male',
                'category' => 'all',
                'max_participants' => 1,
                'has_qualifying_round' => false,
                'has_multiple_attempts' => true,
                'attempts_count' => 3,
                'is_relay' => false,
                'order' => 15,
            ],
            [
                'event_category_id' => $field->id,
                'name' => 'Lontar Peluru',
                'type' => 'individual',
                'gender' => 'female',
                'category' => 'all',
                'max_participants' => 1,
                'has_qualifying_round' => false,
                'has_multiple_attempts' => true,
                'attempts_count' => 3,
                'is_relay' => false,
                'order' => 16,
            ],
            [
                'event_category_id' => $field->id,
                'name' => 'Lempar Cakera',
                'type' => 'individual',
                'gender' => 'male',
                'category' => 'all',
                'max_participants' => 1,
                'has_qualifying_round' => false,
                'has_multiple_attempts' => true,
                'attempts_count' => 3,
                'is_relay' => false,
                'order' => 17,
            ],
            [
                'event_category_id' => $field->id,
                'name' => 'Lempar Cakera',
                'type' => 'individual',
                'gender' => 'female',
                'category' => 'all',
                'max_participants' => 1,
                'has_qualifying_round' => false,
                'has_multiple_attempts' => true,
                'attempts_count' => 3,
                'is_relay' => false,
                'order' => 18,
            ],
            [
                'event_category_id' => $field->id,
                'name' => 'Rejam Lembing',
                'type' => 'individual',
                'gender' => 'male',
                'category' => 'all',
                'max_participants' => 1,
                'has_qualifying_round' => false,
                'has_multiple_attempts' => true,
                'attempts_count' => 3,
                'is_relay' => false,
                'order' => 19,
            ],
            [
                'event_category_id' => $field->id,
                'name' => 'Rejam Lembing',
                'type' => 'individual',
                'gender' => 'female',
                'category' => 'all',
                'max_participants' => 1,
                'has_qualifying_round' => false,
                'has_multiple_attempts' => true,
                'attempts_count' => 3,
                'is_relay' => false,
                'order' => 20,
            ],
            [
                'event_category_id' => $field->id,
                'name' => 'Lompat Tinggi',
                'type' => 'individual',
                'gender' => 'male',
                'category' => 'all',
                'max_participants' => 1,
                'has_qualifying_round' => false,
                'has_multiple_attempts' => true,
                'attempts_count' => 3,
                'is_relay' => false,
                'order' => 21,
            ],
            [
                'event_category_id' => $field->id,
                'name' => 'Lompat Tinggi',
                'type' => 'individual',
                'gender' => 'female',
                'category' => 'all',
                'max_participants' => 1,
                'has_qualifying_round' => false,
                'has_multiple_attempts' => true,
                'attempts_count' => 3,
                'is_relay' => false,
                'order' => 22,
            ],
            [
                'event_category_id' => $field->id,
                'name' => 'Lompat Jauh',
                'type' => 'individual',
                'gender' => 'male',
                'category' => 'all',
                'max_participants' => 1,
                'has_qualifying_round' => false,
                'has_multiple_attempts' => true,
                'attempts_count' => 3,
                'is_relay' => false,
                'order' => 23,
            ],
            [
                'event_category_id' => $field->id,
                'name' => 'Lompat Jauh',
                'type' => 'individual',
                'gender' => 'female',
                'category' => 'all',
                'max_participants' => 1,
                'has_qualifying_round' => false,
                'has_multiple_attempts' => true,
                'attempts_count' => 3,
                'is_relay' => false,
                'order' => 24,
            ],
            [
                'event_category_id' => $field->id,
                'name' => 'Lompat Kijang',
                'type' => 'individual',
                'gender' => 'male',
                'category' => 'all',
                'max_participants' => 1,
                'has_qualifying_round' => false,
                'has_multiple_attempts' => true,
                'attempts_count' => 3,
                'is_relay' => false,
                'order' => 25,
            ],
            [
                'event_category_id' => $field->id,
                'name' => 'Lompat Kijang',
                'type' => 'individual',
                'gender' => 'female',
                'category' => 'all',
                'max_participants' => 1,
                'has_qualifying_round' => false,
                'has_multiple_attempts' => true,
                'attempts_count' => 3,
                'is_relay' => false,
                'order' => 26,
            ],
            [
                'event_category_id' => $funGames->id,
                'name' => 'Lari Bergalah',
                'type' => 'individual',
                'gender' => 'male',
                'category' => 'all',
                'max_participants' => 1,
                'has_qualifying_round' => false,
                'has_multiple_attempts' => false,
                'attempts_count' => 1,
                'is_relay' => false,
                'order' => 27,
            ],
            [
                'event_category_id' => $funGames->id,
                'name' => 'Lari Bergalah',
                'type' => 'individual',
                'gender' => 'female',
                'category' => 'all',
                'max_participants' => 1,
                'has_qualifying_round' => false,
                'has_multiple_attempts' => false,
                'attempts_count' => 1,
                'is_relay' => false,
                'order' => 28,
            ],
            [
                'event_category_id' => $funGames->id,
                'name' => 'Tarik Tali',
                'type' => 'individual',
                'gender' => 'mixed',
                'category' => 'all',
                'max_participants' => 8,
                'has_qualifying_round' => true,
                'has_multiple_attempts' => false,
                'attempts_count' => 1,
                'is_relay' => false,
                'order' => 29,
            ],
            [
                'event_category_id' => $funGames->id,
                'name' => 'Lari Berkayu',
                'type' => 'individual',
                'gender' => 'male',
                'category' => 'all',
                'max_participants' => 1,
                'has_qualifying_round' => false,
                'has_multiple_attempts' => false,
                'attempts_count' => 1,
                'is_relay' => false,
                'order' => 30,
            ],
        ];

        foreach ($templates as $template) {
            EventTemplate::create($template);
        }
    }
}
